name: 构建ARM64基本系统
on: [push] 
jobs:
  默认动作:
    runs-on: ubuntu-latest
    steps:
      - name: skip
        run: touch rootfs.tar.xz
      - name: 打包文件
        run: |
             sudo chmod 777 rootfs.tar.xz
             echo success
             echo "ReleaseVersion=0.1" >> $GITHUB_ENV
      - name: 发布Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.ReleaseVersion }}
          title: ${{ env.ReleaseVersion }}
          prerelease: false
          files: |
            rootfs.tar.xz
