name: learn-action
on: [push]
jobs:
  Explore-action:
    runs-on: ubuntu-18.04
    steps:
      - run: echo Hello world !
      - name: 运行命令.
        run: echo 1111111111
      - run: pwd
      - name: 以root身份运行命令
        run: sudo -u root bash -c whoami
      - run: sudo apt update
      - run: ls -la
