name: learn-action
on: [push]
jobs:
  Explore-action:
    runs-on: ubuntu-18.04
    steps:
      - run: echo Hello world !
      - name: Run command.
        run: echo 1111111111
      - run: pwd
      - run: ls -la
