name: 构建ARM64基本系统
on: [push]
jobs:
  Default-action:
    runs-on: ubuntu-18.04
    steps:
      - name: 安装必要依赖，准备环境
        run: |
             sudo apt update
             sudo apt install qemu-user-static debootstrap -y
      - name: 开始构建基本系统:ARM64
        run: sudo debootstrap --arch arm64 buster arm64/
      - name: 清理文件
        run: sudo rm -rf arm64/
