name: 构建ARM64基本系统
on: 
 push:
  tags:
      - "v*.*.*"
jobs:
  默认动作:
    runs-on: ubuntu-latest
    steps:
      - name: skip
        run: touch rootfs.tar.xz
      - name: 打包文件
        run: sudo chmod 777 rootfs.tar.xz
      - name: 发布Release
        uses: softprops/action-gh-release@v1
        with:
          files: rootfs.tar.xz
